version: '3.8'
services:
  postgres-beautique:
    image: postgres:latest
    hostname: postgres-beautique
    environment:
      POSTGRES_DB: beautique
      POSTGRES_USER: beautique
      POSTGRES_PASSWORD: beautique
    volumes:
      - /db-beautique:/var/lib/postgresql/data
      - ./init-beautique-schema.sql:/docker-entrypoint-initdb.d/init-beautique-schema.sql
    ports:
      - '3334:5432'
    networks:
      - beautique-network
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistent data volume

volumes:
  rabbitmq_data:
networks:
  beautique-network:
    driver: bridge